AWSTemplateFormatVersion: '2010-09-09'
Description: Plantilla base de CloudFormation para una VPC con una subred privada y una subred pública, con parámetros.

Parameters:
  VpcCidr:
    Description: El bloque CIDR para la VPC
    Type: String
    Default: 10.40.0.0/16
    AllowedPattern: ^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$
    ConstraintDescription: debe ser un bloque CIDR válido.
    
  VpcName:
    Description: El nombre de la VPC
    Type: String
    Default: MyVPC
    
  PublicSubnetCidr:
    Description: El bloque CIDR para la subred pública
    Type: String
    Default: 10.40.1.0/24
    AllowedPattern: ^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$
    ConstraintDescription: debe ser un bloque CIDR válido.

  PublicSubnetName:
    Description: El nombre de la subred pública
    Type: String
    Default: MyPublicSubnet

  PrivateSubnetCidr:
    Description: El bloque CIDR para la subred privada
    Type: String
    Default: 10.40.2.0/24
    AllowedPattern: ^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$
    ConstraintDescription: debe ser un bloque CIDR válido.

  PrivateSubnetName:
    Description: El nombre de la subred privada
    Type: String
    Default: MyPrivateSubnet

Resources:
  # VPC
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VpcName

  # Internet Gateway
  MyInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: MyInternetGateway

  # Attach Internet Gateway to VPC
  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  # Public Subnet
  MyPublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Ref PublicSubnetName

  # Private Subnet
  MyPrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
        - Key: Name
          Value: !Ref PrivateSubnetName

  # Route Table for Public Subnet
  MyPublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: MyPublicRouteTable

  # Route Table for Private Subnet
  MyPrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: MyPrivateRouteTable

  # Route to Internet Gateway in Public Route Table
  PublicRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref MyPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  # Associate Public Subnet with Public Route Table
  PublicSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref MyPublicSubnet
      RouteTableId: !Ref MyPublicRouteTable

  # Associate Private Subnet with Private Route Table
  PrivateSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref MyPrivateSubnet
      RouteTableId: !Ref MyPrivateRouteTable

Outputs:
  VpcId:
    Description: ID de la VPC
    Value: !Ref MyVPC
  PublicSubnetId:
    Description: ID de la subred pública
    Value: !Ref MyPublicSubnet
  PrivateSubnetId:
    Description: ID de la subred privada
    Value: !Ref MyPrivateSubnet
  InternetGatewayId:
    Description: ID del Internet Gateway
    Value: !Ref MyInternetGateway
